insert new health check rules

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -36,5 +36,13 @@ jobs:
 
       - name: Health Check
         run: |
-          sleep 10
-          curl localhost:8080/health
+          for i in {1..10}; do
+            if curl -s http://localhost:8080/health; then
+              echo "App is up!"
+              exit 0
+            fi
+            echo "Waiting for app..."
+            sleep 3
+          done
+          echo "App failed to start"
+          exit 1
